"""empty message

Revision ID: 400ea9ace80d
Revises: d0f30013dd2d
Create Date: 2021-03-02 09:35:46.934362

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '400ea9ace80d'
down_revision = 'd0f30013dd2d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('question', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text("'1'"))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('question', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text("'1'"))

    # ### end Alembic commands ###
